#!/bin/sh

## This is a user-script for qutebrowser
## to quickly add a URL to my to-be-ytv.list
## note: ytv stands for 'youtube-dl <audio>'

TBYtvList="$HOME/.nb/list/to-be-ytv.list"
yt_link_info "$QUTE_URL" >> "$TBYtvList" || echo " $(date) ___ $QUTE_URL" >> $TBYtvList

exit
