#!/bin/bash

# I wrote this script to help me compress my audio (.mp3) files.

bitrates=$1 ; shift ;
InputFile=("$@") ;

for i in "${InputFile[@]}"; do
	ffmpeg -i "$i" -ab "$bitrates" "[$bitrates]-$i.mp3";
done

exit
